### ISSUE TITLE
Is it OK to make files pass gofmt

### ISSUE THREAD

**Issue by kmpm** [timabell/schema-explorer#13]
If you run gofmt or use an editor like vscode with the go extensions installed you will find that a lot of files should or would be changed.
So far I haven't found anything but changes in order of imports but I haven't checked the details on all.
I know gofmt is not everyone's cup of tea but it seems as if the community often use it.  
Is it OK to go ahead and fix this? 
I don't want to do the work if the PR would get rejected.

```
gofmt -l .    
driver_interface\driverInterface.go
driver_interface\peek.go
mssql\mssql.go
mysql\mysql.go
options\SseOptions.go
params\params.go
pg\pg.go
reader\dbReader.go
render\render.go
serve\host.go
serve\router.go
serve\setup-handlers.go
serve\table-handlers.go
serve\trail.go
sqlite\sqlite.go
sse_test.go
```

**Comment by timabell** [comment]
gofmt all done now
