### ISSUE TITLE
mssql - missing linebreaks in multi-line nvarchar content

### ISSUE THREAD

**Issue by aisbergde** [timabell/schema-explorer#43]
line breaks are removed from multiline nvarchar content.
original:

```sql
--ATTENTION, destructive!
--we should delete only usp definitions for persistence!
DELETE u
FROM [repo].[GeneratorUsp] [u]
WHERE LEFT([u].[usp_name], 12) = 'usp_PERSIST_'
 AND NOT EXISTS (
  SELECT 1
  FROM [repo].[RepoObject_gross] AS [ro]
  WHERE [u].[usp_schema] = [ro].[RepoObject_schema_name]
   AND [u].[usp_name] = [ro].[usp_persistence_name]
  )
```

shown in browser:
![image](https://user-images.githubusercontent.com/9020187/108757531-3c9ec580-754a-11eb-9ee0-e835bcd7d0d8.png)

**Comment by timabell** [comment]
That's probably just the browser stripping them when rendering, have a look at the source for the rendered page and see if the line-breaks are there in the generated markup, if they are then you could fix it with `white-space: pre;` css. You can edit the css without recompiling the app.

**Comment by aisbergde** [comment]
Thanks for pointing out where to look!
I changed the see.css and now I get the line breaks 

```css
td .bare-value{
    display: inline-block;
    padding: 0.5em 0;
    white-space: break-spaces;
}
```
