### ISSUE TITLE
mssql - lookup tables: a combination of 2 columns is shown, but what is the logic behind?

### ISSUE THREAD

**Issue by aisbergde** [timabell/schema-explorer#44]
original data in ssms
![image](https://user-images.githubusercontent.com/9020187/108758074-f0a05080-754a-11eb-8e95-c682514fab1d.png)

and this is shown in schema-explorer
![image](https://user-images.githubusercontent.com/9020187/108758246-2b09ed80-754b-11eb-92b3-107d326abd0b.png)
we see
1 - [usp_id]
2 - content of [usp_name]
3 - content of [usp_fullname]

and this is the content of the lookup table
![image](https://user-images.githubusercontent.com/9020187/108758674-a8356280-754b-11eb-8a1e-761d60c225f4.png)

Maybe this is related to the fact, that "3" is a calculated column?
But why "2" is included, but the [usp_schema] is not included?
It is a strange logic.

```sql
CREATE TABLE [repo].[GeneratorUsp](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[usp_schema] [nvarchar](128) NOT NULL,
	[usp_name] [nvarchar](128) NOT NULL,
	[has_logging] [tinyint] NOT NULL,
	[usp_Description] [nvarchar](4000) NULL,
	[usp_fullname]  AS (concat('[',[usp_schema],'].[',[usp_name],']')) PERSISTED NOT NULL,
 CONSTRAINT [PK_GeneratorUsp] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_GeneratorUsp_Schema_Name] UNIQUE NONCLUSTERED 
(
	[usp_schema] ASC,
	[usp_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [repo].[GeneratorUsp] ADD  CONSTRAINT [DF_GeneratorUsp_has_logging]  DEFAULT ((1)) FOR [has_logging]
GO
```

**Comment by timabell** [comment]
You've discovered the "peek" feature, which use some regexes to guess which columns might be good to show without having to drill in.

You can find the default rules https://github.com/timabell/schema-explorer/blob/d93498755ca57d93fbf8a2496fccb859f7ad70a1/config/peek-config.txt and you can customize it to suit your particular database if that's useful.
