### ISSUE TITLE
Test mssql without messing with description of dbo.person

### ISSUE THREAD

**Issue by kmpm** [timabell/schema-explorer#9]
I would very much like to be able to test mssql without having to run `test-db-ms_description.sql` between every run.
That would make life easier when automating tests on windows.

On the second and following run I get the following.
```
--- FAIL: Test_ReadSchema (0.36s)
    sse_test.go:81: Checking table fks
    sse_test.go:84: Checking table pks
    sse_test.go:87: Checking table compound-pks
    sse_test.go:90: Checking nullable info
    sse_test.go:93: Checking indexes
    sse_test.go:97: Checking descriptions
    sse_test.go:448: Expected description for table 'dbo.person' of 'somebody to love', got ''
```

**Comment by timabell** [comment]
Tests should be able to guarantee they start from a clean state. Restoring state is fragile, and liable to result in contaminated state that  you can no longer rely on. The correct approach is to ensure your build and test systems guarantee a clean state for every test run, as opposed to carefully trying to put everything back how it was.
